name: efi-tools-ijohnson
base: core20
version: "0.1"
summary: UEFI tools
description: |
  A devmode snap used to test various efi things in an ubuntu core system. 
  Probably could be strict at some point, needs additional accesses beyond 
  system-observe.

# not available on s390x or ppc64el
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

grade: stable
confinement: devmode

apps:
  efivar:
    command: usr/bin/efivar
    plugs:
      - system-observe
  efibootmgr:
    command: bin/efibootmgr
    plugs:
      - system-observe
  efibootdump:
    command: bin/efibootdump
    plugs:
      - system-observe

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
    stage-packages:
      - efivar
      - efibootmgr
